name: Update dependency

on:
  repository_dispatch:
    types: update-dependency

jobs:
  update_version:
    name: Update contracts-interface version
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/synthetixio/docker-sec-tools/alpine:14.17
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}

    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2

      - name: Set npm cache directory
        run: npm config set cache ${{ github.workspace }}/.npm-cache --global 
        continue-on-error: true

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
        continue-on-error: true

      - uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # pin@v2
        id: npm-cache
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
            ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-alpine-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-alpine-node-
        continue-on-error: true

      # fixes permission issues on docker+npm@7
      - name: Chown workspace
        run: chown -R $(whoami) .

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit --no-optional
        env:
          NODE_OPTIONS: --max_old_space_size=7168

      - name: Update @synthetixio/contracts-interface dependency
        run: npm install @synthetixio/contracts-interface@${{ github.event.client_payload.version }} --save-exact

      - name: Commit changes
        run: |
          git config --global user.email "team@synthetix.io" && git config --global user.name "Synthetix Team"
          git commit -am 'contracts-interface@${{ github.event.client_payload.version }}'
          git push origin dev
